version: '3' 
services: 
  toyspg: 
    image: postgres:alpine 
    ports:
      - '5432:5432'
    container_name: 'toyspg'
    restart: always 
    volumes:
      - toyspg-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: pguser  
      POSTGRES_PASSWORD: pgpassword
      
volumes:
  toyspg-data:      
  